### PR TITLE
Build-kite agent builder for hyper-v

### PR DESCRIPTION
**Pull request by weshinsley**
So far, we have just a top-level "build" script, which can built a single agent by id, or a range of agents by id, depending on whether you supply it with 1 or 2 args...

I guess we also want restart/destroy scripts next?

### CODE REVIEW

**Comment by weshinsley** [comment]
I seem only able to request one reviewer! @richfitz and @r-ash

**Comment by richfitz** [comment]
The trick is to select another after selecting the first

**Comment by richfitz** [comment]
oh wow, that's *weird*

**Review by r-ash — APPROVED** [review]
This looks good. Does this deprecate https://github.com/reside-ic/buildkite-agent or are we expecting to still run some agents on linux servers? In which case we will have to maintain both of these repos? We should definitely at least link to this repo from there.

**Comment by richfitz** [comment]
Sorry @r-ash, there was some off-github discussion about this, and we're looking at #2 for now, which moves the loop out of powershell into the Vagrantfile

I think we'll probably consolidate the workers onto the VM for now, particularly if we get more of them

**Comment by richfitz** [comment]
closed in favour of #2

**Pull request closed without merging**
